## Requirement, Structure of the task, Import Data

# Requirements of Amy
Amy Williams        | Seller      | Mafiosi, sells several central houses(top10%) over time, needs average outskirt houses over time to hide from the FBI  

# Important Columns of Data Set (Roland)
- **dateDate** - date the house was sold
- **pricePrice** - prediction targe
- **yr_built** - Built Year
- **yr_renovated** - Year when house was renovated
- **zipcode** - zip
- **lat** - Latitude coordinate
- **long** - Longitude coordinate



What is central?
What is outskirt?
What is 10%? luxorious?
The price sold over time? (to analyse the best time? Seasons when the houses where sold)
- We need the date?
- We need the price?
- What is central?



# Column Names and descriptions for King County Data Set
- **id** - unique identifier for a house
- **dateDate** - date the house was sold
- **pricePrice** - prediction target
- **bedroomsNumber** - # of bedrooms
- **bathroomsNumber** - # of bathrooms
- **sqft_livingsquare** - footage of the home
- **sqft_lotsquare** - footage of the lot
- **floorsTotal** - floors (levels) in house
- **waterfront** - House which has a view to a waterfront
- **view** - quality of view
- **condition** - How good the condition is ( Overall )
- **grade** - overall grade given to the housing unit, based on King County grading system
- **sqft_above** - square footage of house apart from basement
- **sqft_basement** - square footage of the basement
- **yr_built** - Built Year
- **yr_renovated** - Year when house was renovated
- **zipcode** - zip
- **lat** - Latitude coordinate
- **long** - Longitude coordinate
- **sqft_living15** - The square footage of interior housing living space for the nearest 15 neighbors
- **sqft_lot15** - The square footage of the land lots of the nearest 15 neighbors

In [2]:
import numpy as np
import pandas as pd

In [12]:
# importing raw data

df_amy = pd.read_csv("/Users/rolandelsaesser/neuefische_course/eda_template/data/dataset.csv")
df_copy = df_amy.copy()

In [13]:
# your code: check for data types and statistics overview of data frame columns

# 1. Check data types, non-null counts, and memory usage
print("--- Data Info ---")
df_copy.info()

--- Data Info ---
<class 'pandas.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           21597 non-null  str
 1   price          21597 non-null  float64
 2   house_id       21597 non-null  int64
 3   id             21597 non-null  int64
 4   id.1           21597 non-null  int64
 5   bedrooms       21597 non-null  float64
 6   bathrooms      21597 non-null  float64
 7   sqft_living    21597 non-null  float64
 8   sqft_lot       21597 non-null  float64
 9   floors         21597 non-null  float64
 10  waterfront     19206 non-null  float64
 11  view           21534 non-null  float64
 12  condition      21597 non-null  int64
 13  grade          21597 non-null  int64
 14  sqft_above     21597 non-null  float64
 15  sqft_basement  21145 non-null  float64
 16  yr_built       21597 non-null  int64
 17  yr_renovated   17749 non-null  float64
 18  zipcode        21597 non-null  int64
 19  lat            21597 non-null  float64
 20  long           21597 non-null  float64
 21  sqft_living15  21597 non-null  float64
 22  sqft_lot15     21597 non-null  float64
dtypes: float64(15), int64(7), str(1)
memory usage: 3.8 MB

In [14]:
# 2. Get statistical summary for numerical columns
print("\n--- Numerical Summary ---")
display(df_copy.describe())

--- Numerical Summary ---

,price,house_id,id,id.1,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.159700e+04,2.159700e+04,21597.000000,2.159700e+04,21597.000000,21597.000000,21597.000000,2.159700e+04,21597.000000,19206.000000,...,21597.000000,21597.000000,21145.000000,21597.000000,17749.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000
mean,5.402966e+05,4.580474e+09,10799.000000,4.580474e+09,3.373200,2.115826,2080.321850,1.509941e+04,1.494096,0.007602,...,7.657915,1788.596842,291.857224,1970.999676,836.650516,98077.951845,47.560093,-122.213983,1986.620318,12758.283512
std,3.673681e+05,2.876736e+09,6234.661218,2.876736e+09,0.926299,0.768984,918.106125,4.141264e+04,0.539683,0.086858,...,1.173200,827.759761,442.490863,29.375234,4000.110554,53.513072,0.138552,0.140724,685.230472,27274.441950
min,7.800000e+04,1.000102e+06,1.000000,1.000102e+06,1.000000,0.500000,370.000000,5.200000e+02,1.000000,0.000000,...,3.000000,370.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,3.220000e+05,2.123049e+09,5400.000000,2.123049e+09,3.000000,1.750000,1430.000000,5.040000e+03,1.000000,0.000000,...,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471100,-122.328000,1490.000000,5100.000000
50%,4.500000e+05,3.904930e+09,10799.000000,3.904930e+09,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,...,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.231000,1840.000000,7620.000000
75%,6.450000e+05,7.308900e+09,16198.000000,7.308900e+09,4.000000,2.500000,2550.000000,1.068500e+04,2.000000,0.000000,...,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,7.700000e+06,9.900000e+09,21597.000000,9.900000e+09,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,...,13.000000,9410.000000,4820.000000,2015.000000,20150.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [18]:
# 3. Get statistical summary for categorical/object columns
# (This helps find unique counts and the most frequent labels)
print("\n--- Categorical Summary ---")
display(df_copy.describe(include='object'))

--- Categorical Summary ---

/var/folders/5l/l8tzy9cx1ms0sx8q3bytdn9r0000gn/T/ipykernel_11734/2054843459.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df_copy.describe(include='object'))

              date
count        21597
unique         372
top     2014-06-23
freq           142

In [15]:
# 4. Explicitly check for missing values count per column
print("\n--- Missing Values ---")
print(df_copy.isnull().sum())

--- Missing Values ---
date                0
price               0
house_id            0
id                  0
id.1                0
bedrooms            0
bathrooms           0
sqft_living         0
sqft_lot            0
floors              0
waterfront       2391
view               63
condition           0
grade               0
sqft_above          0
sqft_basement     452
yr_built            0
yr_renovated     3848
zipcode             0
lat                 0
long                0
sqft_living15       0
sqft_lot15          0
dtype: int64

In [19]:
df_copy.head(5)

,date,price,house_id,id,id.1,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,2014-10-13,221900.0,7129300520,1,7129300520,3.0,1.00,1180.0,5650.0,1.0,...,7,1180.0,0.0,1955,0.0,98178,47.5112,-122.257,1340.0,5650.0
1,2014-12-09,538000.0,6414100192,2,6414100192,3.0,2.25,2570.0,7242.0,2.0,...,7,2170.0,400.0,1951,19910.0,98125,47.7210,-122.319,1690.0,7639.0
2,2015-02-25,180000.0,5631500400,3,5631500400,2.0,1.00,770.0,10000.0,1.0,...,6,770.0,0.0,1933,NaN,98028,47.7379,-122.233,2720.0,8062.0
3,2014-12-09,604000.0,2487200875,4,2487200875,4.0,3.00,1960.0,5000.0,1.0,...,7,1050.0,910.0,1965,0.0,98136,47.5208,-122.393,1360.0,5000.0
4,2015-02-18,510000.0,1954400510,5,1954400510,3.0,2.00,1680.0,8080.0,1.0,...,8,1680.0,0.0,1987,0.0,98074,47.6168,-122.045,1800.0,7503.0

In [22]:
# dropping unwanted columns for further analysis (id, id.1, sqft_above, sqft_basement, sqft_living15, sqft_lot15)
df_copy= df_copy.drop(columns=['id', 'id.1', 'sqft_above', 'sqft_basement', 'sqft_living15', 'sqft_lot15'])

In [23]:
df_copy.head(5)

,date,price,house_id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,yr_built,yr_renovated,zipcode,lat,long
0,2014-10-13,221900.0,7129300520,3.0,1.00,1180.0,5650.0,1.0,NaN,0.0,3,7,1955,0.0,98178,47.5112,-122.257
1,2014-12-09,538000.0,6414100192,3.0,2.25,2570.0,7242.0,2.0,0.0,0.0,3,7,1951,19910.0,98125,47.7210,-122.319
2,2015-02-25,180000.0,5631500400,2.0,1.00,770.0,10000.0,1.0,0.0,0.0,3,6,1933,NaN,98028,47.7379,-122.233
3,2014-12-09,604000.0,2487200875,4.0,3.00,1960.0,5000.0,1.0,0.0,0.0,5,7,1965,0.0,98136,47.5208,-122.393
4,2015-02-18,510000.0,1954400510,3.0,2.00,1680.0,8080.0,1.0,0.0,0.0,3,8,1987,0.0,98074,47.6168,-122.045

In [24]:
# dropping unwanted columns for further analysis (yr_renovated))
df_copy= df_copy.drop(columns=['yr_renovated'])

In [25]:
df_copy.head(5)

,date,price,house_id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,yr_built,zipcode,lat,long
0,2014-10-13,221900.0,7129300520,3.0,1.00,1180.0,5650.0,1.0,NaN,0.0,3,7,1955,98178,47.5112,-122.257
1,2014-12-09,538000.0,6414100192,3.0,2.25,2570.0,7242.0,2.0,0.0,0.0,3,7,1951,98125,47.7210,-122.319
2,2015-02-25,180000.0,5631500400,2.0,1.00,770.0,10000.0,1.0,0.0,0.0,3,6,1933,98028,47.7379,-122.233
3,2014-12-09,604000.0,2487200875,4.0,3.00,1960.0,5000.0,1.0,0.0,0.0,5,7,1965,98136,47.5208,-122.393
4,2015-02-18,510000.0,1954400510,3.0,2.00,1680.0,8080.0,1.0,0.0,0.0,3,8,1987,98074,47.6168,-122.045

In [30]:
df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         21597 non-null  str
 1   price        21597 non-null  float64
 2   house_id     21597 non-null  int64
 3   bedrooms     21597 non-null  float64
 4   bathrooms    21597 non-null  float64
 5   sqft_living  21597 non-null  float64
 6   sqft_lot     21597 non-null  float64
 7   floors       21597 non-null  float64
 8   waterfront   19206 non-null  float64
 9   view         21534 non-null  float64
 10  condition    21597 non-null  int64
 11  grade        21597 non-null  int64
 12  yr_built     21597 non-null  int64
 13  zipcode      21597 non-null  int64
 14  lat          21597 non-null  float64
 15  long         21597 non-null  float64
dtypes: float64(10), int64(5), str(1)
memory usage: 2.6 MB

In [34]:
# in precipitation column, replace NaN with 0, in waterfront column
df_copy.fillna({"waterfront":0})

,date,price,house_id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,yr_built,zipcode,lat,long
0,2014-10-13,221900.0,7129300520,3.0,1.00,1180.0,5650.0,1.0,0.0,0.0,3,7,1955,98178,47.5112,-122.257
1,2014-12-09,538000.0,6414100192,3.0,2.25,2570.0,7242.0,2.0,0.0,0.0,3,7,1951,98125,47.7210,-122.319
2,2015-02-25,180000.0,5631500400,2.0,1.00,770.0,10000.0,1.0,0.0,0.0,3,6,1933,98028,47.7379,-122.233
3,2014-12-09,604000.0,2487200875,4.0,3.00,1960.0,5000.0,1.0,0.0,0.0,5,7,1965,98136,47.5208,-122.393
4,2015-02-18,510000.0,1954400510,3.0,2.00,1680.0,8080.0,1.0,0.0,0.0,3,8,1987,98074,47.6168,-122.045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21592,2014-05-21,360000.0,263000018,3.0,2.50,1530.0,1131.0,3.0,0.0,0.0,3,8,2009,98103,47.6993,-122.346
21593,2015-02-23,400000.0,6600060120,4.0,2.50,2310.0,5813.0,2.0,0.0,0.0,3,8,2014,98146,47.5107,-122.362
21594,2014-06-23,402101.0,1523300141,2.0,0.75,1020.0,1350.0,2.0,0.0,0.0,3,7,2009,98144,47.5944,-122.299
21595,2015-01-16,400000.0,291310100,3.0,2.50,1600.0,2388.0,2.0,0.0,0.0,3,8,2004,98027,47.5345,-122.069
21596,2014-10-15,325000.0,1523300157,2.0,0.75,1020.0,1076.0,2.0,0.0,0.0,3,7,2008,98144,47.5941,-122.299

In [37]:
# The capital 'I' makes it the nullable integer type
df_copy['waterfront'] = df_copy['waterfront'].astype('Int64')

In [40]:
df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         21597 non-null  str
 1   price        21597 non-null  float64
 2   house_id     21597 non-null  int64
 3   bedrooms     21597 non-null  float64
 4   bathrooms    21597 non-null  float64
 5   sqft_living  21597 non-null  float64
 6   sqft_lot     21597 non-null  float64
 7   floors       21597 non-null  float64
 8   waterfront   19206 non-null  Int64
 9   view         21534 non-null  float64
 10  condition    21597 non-null  int64
 11  grade        21597 non-null  int64
 12  yr_built     21597 non-null  int64
 13  zipcode      21597 non-null  int64
 14  lat          21597 non-null  float64
 15  long         21597 non-null  float64
dtypes: Int64(1), float64(9), int64(5), str(1)
memory usage: 2.7 MB

In [42]:
# display number of missing values per column
df_copy.isna().sum()

date              0
price             0
house_id          0
bedrooms          0
bathrooms         0
sqft_living       0
sqft_lot          0
floors            0
waterfront     2391
view             63
condition         0
grade             0
yr_built          0
zipcode           0
lat               0
long              0
dtype: int64

In [39]:
# Convert specific columns to int64
df_copy = df_copy.astype({
    'price': 'int64',
    'house_id': 'int64',
    'bedrooms': 'int64',
    'bathrooms': 'int64',
    'sqft_living': 'int64',
    'sqft_lot': 'int64',
    'floors': 'int64',
    'waterfront': 'int64',
    'view': 'int64',
    'condition': 'int64',
    'grade': 'int64'
})

ValueError: cannot convert NA to integer: Error while type casting for column 'waterfront'